[2024-10-30T23:01:27.619+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T23:01:29.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:55:00+00:00 [queued]>
[2024-10-30T23:01:29.478+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:55:00+00:00 [queued]>
[2024-10-30T23:01:29.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T23:01:29.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sensor_data_generator> on 2024-10-30 22:55:00+00:00
[2024-10-30T23:01:29.611+0000] {standard_task_runner.py:64} INFO - Started process 2013 to run task
[2024-10-30T23:01:29.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_data', 'sensor_data_generator', 'scheduled__2024-10-30T22:55:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/sensor_***.py', '--cfg-path', '/tmp/tmperzbumaa']
[2024-10-30T23:01:29.660+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask sensor_data_generator
[2024-10-30T23:01:30.133+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:55:00+00:00 [running]> on host 5d793f8b441e
[2024-10-30T23:01:30.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='sensor_data' AIRFLOW_CTX_TASK_ID='sensor_data_generator' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T22:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T22:55:00+00:00'
[2024-10-30T23:01:30.807+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T23:01:31.060+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.061+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.061+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:31.085+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.086+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.139+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.161+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.163+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:31.368+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.375+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.534+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.536+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.537+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:31.575+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.579+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.651+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.652+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.652+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:31.721+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.723+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.899+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.901+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:31.901+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:31.946+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:31.950+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.022+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.025+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.027+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:32.046+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.047+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.099+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.108+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.116+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:32.257+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.258+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.489+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.490+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.491+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:32.549+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.550+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.596+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.597+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.598+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:32.635+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.636+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.655+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.657+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.659+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:01:32.675+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:01:32.681+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:01:32.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T23:01:32.684+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sensor_airflow.py", line 24, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:9092'], max_block_ms=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-30T23:01:32.798+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sensor_data, task_id=sensor_data_generator, run_id=scheduled__2024-10-30T22:55:00+00:00, execution_date=20241030T225500, start_date=20241030T230129, end_date=20241030T230132
[2024-10-30T23:01:33.090+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task sensor_data_generator (NoBrokersAvailable; 2013)
[2024-10-30T23:01:33.176+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-30T23:01:33.360+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T23:01:33.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
