[2024-10-30T22:55:20.095+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T22:55:20.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:50:00+00:00 [queued]>
[2024-10-30T22:55:20.943+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:50:00+00:00 [queued]>
[2024-10-30T22:55:20.944+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T22:55:21.296+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sensor_data_generator> on 2024-10-30 22:50:00+00:00
[2024-10-30T22:55:21.359+0000] {standard_task_runner.py:64} INFO - Started process 1843 to run task
[2024-10-30T22:55:21.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_data', 'sensor_data_generator', 'scheduled__2024-10-30T22:50:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/sensor_***.py', '--cfg-path', '/tmp/tmpmh1n_j79']
[2024-10-30T22:55:21.587+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask sensor_data_generator
[2024-10-30T22:55:22.475+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T22:50:00+00:00 [running]> on host 5d793f8b441e
[2024-10-30T22:55:23.791+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='sensor_data' AIRFLOW_CTX_TASK_ID='sensor_data_generator' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T22:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T22:50:00+00:00'
[2024-10-30T22:55:23.793+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T22:55:23.942+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:23.951+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:23.971+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.037+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.038+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.115+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.120+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.126+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.190+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.190+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.269+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.272+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.273+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.373+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.376+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.416+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.417+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.418+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.479+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.481+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.524+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.525+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.526+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.574+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.578+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.708+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.714+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.715+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:24.760+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.761+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.853+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:24.853+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:24.854+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:25.028+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.029+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.135+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.138+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.139+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:25.177+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.181+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.206+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.235+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.236+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:25.334+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.336+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.362+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.362+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.365+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T22:55:25.374+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T22:55:25.374+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T22:55:25.375+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T22:55:25.375+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sensor_airflow.py", line 24, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:9092'], max_block_ms=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-30T22:55:25.409+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sensor_data, task_id=sensor_data_generator, run_id=scheduled__2024-10-30T22:50:00+00:00, execution_date=20241030T225000, start_date=20241030T225520, end_date=20241030T225525
[2024-10-30T22:55:25.519+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task sensor_data_generator (NoBrokersAvailable; 1843)
[2024-10-30T22:55:25.681+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-30T22:55:26.762+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T22:55:26.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
