[2024-11-13T13:18:34.174+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T13:18:34.945+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_data_incremental.fetch_data_from_api scheduled__2024-11-13T13:17:00+00:00 [queued]>
[2024-11-13T13:18:35.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_data_incremental.fetch_data_from_api scheduled__2024-11-13T13:17:00+00:00 [queued]>
[2024-11-13T13:18:35.021+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T13:18:36.605+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data_from_api> on 2024-11-13 13:17:00+00:00
[2024-11-13T13:18:36.638+0000] {standard_task_runner.py:64} INFO - Started process 1157 to run task
[2024-11-13T13:18:36.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_data_incremental', 'fetch_data_from_api', 'scheduled__2024-11-13T13:17:00+00:00', '--job-id', '696', '--raw', '--subdir', 'DAGS_FOLDER/***_producer.py', '--cfg-path', '/tmp/tmplphjc5k0']
[2024-11-13T13:18:36.670+0000] {standard_task_runner.py:91} INFO - Job 696: Subtask fetch_data_from_api
[2024-11-13T13:18:37.514+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_data_incremental.fetch_data_from_api scheduled__2024-11-13T13:17:00+00:00 [running]> on host b51985a4b8f1
[2024-11-13T13:18:39.355+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='fetch_data_incremental' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T13:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-13T13:17:00+00:00'
[2024-11-13T13:18:39.358+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T13:18:39.684+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: connecting to 10.0.2.15:9092 [('10.0.2.15', 9092) IPv4]
[2024-11-13T13:18:39.716+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: Connection complete.
[2024-11-13T13:18:45.334+0000] {airflow_producer.py:114} INFO - Fetched 100 records from API with offset 0
[2024-11-13T13:18:45.358+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T13:18:45.367+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_producer.py", line 127, in stream_data
    if offset >= total_count:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
[2024-11-13T13:18:45.722+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_data_incremental, task_id=fetch_data_from_api, run_id=scheduled__2024-11-13T13:17:00+00:00, execution_date=20241113T131700, start_date=20241113T131834, end_date=20241113T131845
[2024-11-13T13:18:45.835+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 696 for task fetch_data_from_api ('>=' not supported between instances of 'int' and 'NoneType'; 1157)
[2024-11-13T13:18:45.902+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-13T13:18:46.012+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T13:18:46.033+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
